name: Gerar APK - Minha Mercearia

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Preparar projeto
        run: |
       unzip -q MinhaMerceariaAndroid_com_icone_carrinho.zip
          cp -r MinhaMerceariaAndroid/. .
          rm -rf MinhaMerceariaAndroid

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verificar Android SDK
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          ls "$ANDROID_HOME"

      - name: Gerar APK
        run: |
          gradle assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: MinhaMercearia-APK
          path: app/build/outputs/apk/debug/app-debug.apk
